set(DLIB_INCLUDE_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/dlib-19.17/Install/Release/include")
set(DLIB_LIBRARY_DEBUG_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/dlib-19.17/Install/Debug/lib/libdlib.a")
set(DLIB_LIBRARY_OPTIMIZED_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/dlib-19.17/Install/Release/lib/libdlib.a")
set(PYTHON_INCLUDE_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/Python-3.6.7/include/python3.6m")
set(PYTHON_LIBRARY_DEBUG_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/Python-3.6.7/lib/libpython3.6m.a")
set(PYTHON_LIBRARY_OPTIMIZED_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/Python-3.6.7/lib/libpython3.6m.a")
