set(DLIB_INCLUDE_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/dlib-19.17/Install/include")
set(DLIB_LIBRARY_DEBUG_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/dlib-19.17/Install/lib/dlib19.17.0_debug_32bit_msvc1916.lib")
set(DLIB_LIBRARY_OPTIMIZED_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/dlib-19.17/Install/lib/dlib19.17.0_release_32bit_msvc1916.lib")
set(PYTHON_LIBRARY_DEBUG_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/Python-3.7.2/PCbuild/win32/python37.lib")
set(PYTHON_LIBRARY_OPTIMIZED_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/Python-3.7.2/PCbuild/win32/python37.lib")
